# Three secrets, filled three different ways on purpose.
#
# The signing key is generated ephemerally and sent to Secrets Manager through
# a write-only argument. Terraform uses it during apply but never stores it in
# the plan or state.
#
# The datastore credentials are generated by Terraform, because it has to know
# them to create the database and the instance in the first place. Those do
# land in state, which is why the state bucket is encrypted, versioned and
# blocked from public access. Rotate them through the console if the state file
# is ever mishandled.

resource "aws_secretsmanager_secret" "jwt" {
  name                    = "${local.name}/jwt-secret"
  description             = "HS256 key generated ephemerally by Terraform for access tokens."
  recovery_window_in_days = var.destroy_friendly ? 0 : 7
}

ephemeral "random_password" "jwt" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id                = aws_secretsmanager_secret.jwt.id
  secret_string_wo         = ephemeral.random_password.jwt.result
  secret_string_wo_version = var.jwt_secret_version
}

# The OpenAI key is a third case: created and filled outside Terraform, and only
# looked up here. It is a real credential that CI would otherwise have to carry
# on every apply, and a data source puts nothing but the ARN in state. Create it
# once, before the first apply that includes this:
#   aws secretsmanager create-secret --name sciterm/openai-api-key --secret-string ...
data "aws_secretsmanager_secret" "openai" {
  name = "${local.name}/openai-api-key"
}

resource "random_password" "db" {
  length = 40
  # RDS rejects several punctuation characters in a master password, and a DSN
  # would need them percent-encoded anyway.
  special = false
}

# Stored as the whole DSN rather than the password alone: the app takes one
# `DATABASE_URL` string, so composing it here keeps the task definition from
# having to assemble a secret out of parts.
resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${local.name}/database-url"
  recovery_window_in_days = var.destroy_friendly ? 0 : 7
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgresql://${aws_db_instance.main.username}:${random_password.db.result}@${aws_db_instance.main.endpoint}/${aws_db_instance.main.db_name}"
}
