// Every write goes through Writer, so nothing this tool produces escapes the
// manifest. That is what makes re-runs idempotent, makes --prune safe, and
// makes it impossible to silently overwrite a file a human wrote.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Manifest is the on-disk record of what this tool generated, keyed by
// repo-relative path and valued by the SHA-256 of the content it wrote.
type Manifest struct {
	GeneratedBy string            `json:"generated_by"`
	Note        string            `json:"note"`
	Files       map[string]string `json:"files"`
}

type Writer struct {
	root         string
	dryRun       bool
	force        bool
	manifestPath string

	previous map[string]string
	current  map[string]string

	written []string
	skipped []string
	notes   []string
}

func NewWriter(root string, dryRun, force bool) *Writer {
	w := &Writer{
		root:         root,
		dryRun:       dryRun,
		force:        force,
		manifestPath: filepath.Join(root, ".agents", manifestName),
		previous:     map[string]string{},
		current:      map[string]string{},
	}
	// A manifest that cannot be read is treated as absent rather than fatal:
	// the worst case is that existing files are reported as unmanaged, which
	// fails safe.
	if data, err := os.ReadFile(w.manifestPath); err == nil {
		var manifest Manifest
		if json.Unmarshal(data, &manifest) == nil && manifest.Files != nil {
			w.previous = manifest.Files
		}
	}
	return w
}

func (w *Writer) Note(format string, args ...any) {
	w.notes = append(w.notes, fmt.Sprintf(format, args...))
}

func (w *Writer) rel(path string) string {
	relative, err := filepath.Rel(w.root, path)
	if err != nil {
		return path
	}
	return relative
}

func digestBytes(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

func digestFile(path string) (string, bool) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return digestBytes(content), true
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// managed reports whether this tool may write to path: either it does not
// exist, or an earlier run produced it, or --force was given.
func (w *Writer) managed(rel, path string) bool {
	if !exists(path) || w.force {
		return true
	}
	_, generated := w.previous[rel]
	if !generated {
		w.skipped = append(w.skipped,
			fmt.Sprintf("%s (exists and was not generated by this tool; use --force)", rel))
	}
	return generated
}

// Write emits a fully generated file. It returns false when the path belongs
// to someone else, so callers can skip the rest of that skill.
func (w *Writer) Write(path string, content []byte) bool {
	rel := w.rel(path)
	if !w.managed(rel, path) {
		return false
	}
	digest := digestBytes(content)
	w.current[rel] = digest

	if existing, ok := digestFile(path); ok && existing == digest {
		return true // unchanged, but still manifested
	}
	w.written = append(w.written, rel)
	if w.dryRun {
		return true
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		w.Note("could not create %s: %v", filepath.Dir(rel), err)
		return false
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		w.Note("could not write %s: %v", rel, err)
		return false
	}
	return true
}

func (w *Writer) WriteString(path, content string) bool {
	return w.Write(path, []byte(content))
}

// Copy carries a skill's support file (scripts/, references/, assets/) across
// verbatim, preserving its mode so an executable helper stays executable.
func (w *Writer) Copy(src, dest string) {
	rel := w.rel(dest)
	if !w.managed(rel, dest) {
		return
	}
	content, err := os.ReadFile(src)
	if err != nil {
		w.Note("could not read %s: %v", w.rel(src), err)
		return
	}
	digest := digestBytes(content)
	w.current[rel] = digest
	if existing, ok := digestFile(dest); ok && existing == digest {
		return
	}
	w.written = append(w.written, rel)
	if w.dryRun {
		return
	}
	mode := os.FileMode(0o644)
	if info, err := os.Stat(src); err == nil {
		mode = info.Mode().Perm()
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		w.Note("could not create %s: %v", filepath.Dir(rel), err)
		return
	}
	if err := os.WriteFile(dest, content, mode); err != nil {
		w.Note("could not write %s: %v", rel, err)
	}
}

// WriteBlock inserts generated content into a marked region, leaving anything
// the human wrote around it untouched. This is how CLAUDE.md reaches AGENTS.md
// without taking ownership of the whole file.
func (w *Writer) WriteBlock(path, sourceLabel, blockBody string) {
	begin := fmt.Sprintf(beginTemplate, sourceLabel, tool)
	end := fmt.Sprintf(endTemplate, sourceLabel)
	block := begin + "\n\n" + strings.TrimSpace(blockBody) + "\n\n" + end + "\n"

	existing := ""
	if data, err := os.ReadFile(path); err == nil {
		existing = string(data)
	}

	// Matched by source label, not by generator name: renaming this tool must
	// not orphan the block it already owns and append a second copy beside it.
	// Any duplicate blocks a past rename produced are collapsed into one.
	pattern := regexp.MustCompile("(?s)" +
		regexp.QuoteMeta(fmt.Sprintf("<!-- BEGIN generated from %s by ", sourceLabel)) +
		".*?" + regexp.QuoteMeta(end) + "\n?")

	var content string
	switch {
	case pattern.MatchString(existing):
		content = replaceFirstAndDropRest(pattern, existing, block)
	case strings.TrimSpace(existing) != "":
		content = strings.TrimRight(existing, "\n") + "\n\n" + block
		w.Note("%s already existed; the converted content was appended below your own text "+
			"rather than replacing it.", w.rel(path))
	default:
		content = block
	}

	rel := w.rel(path)
	digest := digestBytes([]byte(content))
	w.current[rel] = digest
	if existingDigest, ok := digestFile(path); ok && existingDigest == digest {
		return
	}
	w.written = append(w.written, rel)
	if w.dryRun {
		return
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		w.Note("could not create %s: %v", filepath.Dir(rel), err)
		return
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		w.Note("could not write %s: %v", rel, err)
	}
}

// replaceFirstAndDropRest substitutes the first match and deletes any others,
// so a block that was duplicated by an earlier rename heals on the next run.
// The replacement is treated as a literal: a "$1" inside generated markdown
// must not be read as a group reference.
func replaceFirstAndDropRest(pattern *regexp.Regexp, text, replacement string) string {
	locations := pattern.FindAllStringIndex(text, -1)
	if len(locations) == 0 {
		return text
	}
	var out strings.Builder
	previous := 0
	for i, location := range locations {
		out.WriteString(text[previous:location[0]])
		if i == 0 {
			out.WriteString(replacement)
		}
		previous = location[1]
	}
	out.WriteString(text[previous:])
	return strings.TrimRight(out.String(), "\n") + "\n"
}

// Prune deletes files an earlier run generated that this run did not, but only
// when their content still matches what was recorded. A file edited by hand
// since is reported and kept.
func (w *Writer) Prune() []string {
	stale := make([]string, 0, len(w.previous))
	for rel := range w.previous {
		if _, still := w.current[rel]; !still {
			stale = append(stale, rel)
		}
	}
	sort.Strings(stale)

	removed := []string{}
	for _, rel := range stale {
		path := filepath.Join(w.root, rel)
		if !exists(path) {
			continue
		}
		digest, ok := digestFile(path)
		if !ok || digest != w.previous[rel] {
			w.skipped = append(w.skipped, fmt.Sprintf("%s (stale, but edited by hand; not deleted)", rel))
			continue
		}
		removed = append(removed, rel)
		if w.dryRun {
			continue
		}
		if err := os.Remove(path); err != nil {
			w.Note("could not delete %s: %v", rel, err)
			continue
		}
		w.removeEmptyParents(filepath.Dir(path))
	}
	return removed
}

// removeEmptyParents walks up from a deleted file, dropping directories that
// the deletion emptied. It stops at the project root, which it never removes.
func (w *Writer) removeEmptyParents(dir string) {
	for dir != w.root && strings.HasPrefix(dir, w.root) {
		entries, err := os.ReadDir(dir)
		if err != nil || len(entries) > 0 {
			return
		}
		if err := os.Remove(dir); err != nil {
			return
		}
		dir = filepath.Dir(dir)
	}
}

// Stale lists paths an earlier run generated that this one did not, and that
// are still on disk -- what --prune would consider.
func (w *Writer) Stale() []string {
	var stale []string
	for rel := range w.previous {
		if _, still := w.current[rel]; still {
			continue
		}
		if exists(filepath.Join(w.root, rel)) {
			stale = append(stale, rel)
		}
	}
	sort.Strings(stale)
	return stale
}

// SaveManifest records this run. The manifest never lists itself: its own
// digest would change every time it was written.
func (w *Writer) SaveManifest() error {
	delete(w.current, w.rel(w.manifestPath))
	if w.dryRun {
		return nil
	}
	payload := Manifest{
		GeneratedBy: tool,
		Note:        "Tracks files generated from the Claude Code config. Do not edit.",
		Files:       w.current,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(w.manifestPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(w.manifestPath, append(data, '\n'), 0o644)
}
