#!/usr/bin/env bash
#
# Resolve the pinned testledger binary and run it.
#
# Copy this into a project as `scripts/testledger.sh`, alongside a
# `testledger.lock` at the project root. The lock is what makes a run
# reproducible: it names one release and the SHA-256 of each platform's binary,
# so CI and a laptop resolve the identical bytes and a tampered or truncated
# download fails loudly instead of executing.
#
#   scripts/testledger.sh check              # forwards every argument
#   scripts/testledger.sh --update-lock v0.2.0
#   TESTLEDGER_BIN=../testledger/bin/testledger scripts/testledger.sh check
#
# The binary is cached under .testledger/bin/, which should be gitignored.

set -euo pipefail

REPO="${TESTLEDGER_REPO:-danielcsee/testledger}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="${TESTLEDGER_LOCK:-$ROOT/testledger.lock}"
CACHE="${TESTLEDGER_CACHE:-$ROOT/.testledger/bin}"

die() { echo "testledger.sh: $*" >&2; exit 1; }

# Platform names match the release asset suffixes exactly.
platform() {
  local os arch
  case "$(uname -s)" in
    Darwin) os=darwin ;;
    Linux)  os=linux ;;
    *) die "unsupported OS $(uname -s); build from source and set TESTLEDGER_BIN" ;;
  esac
  case "$(uname -m)" in
    arm64|aarch64) arch=arm64 ;;
    x86_64|amd64)  arch=amd64 ;;
    *) die "unsupported architecture $(uname -m); build from source and set TESTLEDGER_BIN" ;;
  esac
  echo "${os}-${arch}"
}

lock_value() {
  [ -f "$LOCK" ] || die "no lock file at $LOCK; run: $0 --update-lock <version>"
  # Trailing whitespace and CRLF are stripped: a lock edited on Windows should
  # not produce a checksum that can never match.
  sed -n "s/^$1=//p" "$LOCK" | tr -d ' \t\r' | head -1
}

sha256_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
  elif command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else die "need shasum or sha256sum to verify the download"
  fi
}

# `gh` first: it carries the credentials a private repo needs. curl is the
# fallback for machines that have a token but no gh.
fetch() {
  local version="$1" asset="$2" dest="$3"
  if command -v gh >/dev/null 2>&1; then
    gh release download "$version" --repo "$REPO" --pattern "$asset" --output "$dest" --clobber
  elif [ -n "${GITHUB_TOKEN:-}" ] || [ -n "${GH_TOKEN:-}" ]; then
    local token="${GITHUB_TOKEN:-$GH_TOKEN}"
    local id
    id="$(curl -fsSL -H "Authorization: Bearer $token" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/$REPO/releases/tags/$version" \
      | sed -n "s/.*\"id\": *\([0-9]*\),[^}]*\"name\": *\"$asset\".*/\1/p" | head -1)"
    [ -n "$id" ] || die "release $version has no asset named $asset"
    curl -fsSL -H "Authorization: Bearer $token" \
      -H "Accept: application/octet-stream" \
      "https://api.github.com/repos/$REPO/releases/assets/$id" -o "$dest"
  else
    die "$REPO is private: install gh (and gh auth login), or set GITHUB_TOKEN"
  fi
}

update_lock() {
  local version="$1"
  [ -n "$version" ] || die "--update-lock needs a version, e.g. v0.2.0"
  local tmp
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  fetch "$version" checksums.txt "$tmp/checksums.txt"

  {
    echo "# Generated by scripts/testledger.sh --update-lock $version"
    echo "# Do not edit by hand: these checksums are what make a download verifiable."
    echo "version=$version"
    # checksums.txt is "<sha>  testledger-<os>-<arch>"; keep only real targets.
    awk '{ n = $2; sub(/^testledger-/, "", n); if (n != "") print n "=" $1 }' \
      "$tmp/checksums.txt" | sort
  } > "$LOCK"

  echo "Pinned $REPO $version in $LOCK:"
  sed -n '3,$p' "$LOCK" | sed 's/^/  /'
}

main() {
  if [ "${1:-}" = "--update-lock" ]; then
    update_lock "${2:-}"
    return 0
  fi

  # An explicit override always wins, so a local checkout can be tested against
  # a project without touching the lock.
  if [ -n "${TESTLEDGER_BIN:-}" ]; then
    [ -x "$TESTLEDGER_BIN" ] || die "TESTLEDGER_BIN=$TESTLEDGER_BIN is not executable"
    exec "$TESTLEDGER_BIN" "$@"
  fi

  local plat version expected binary
  plat="$(platform)"
  version="$(lock_value version)"
  expected="$(lock_value "$plat")"
  [ -n "$version" ] || die "no version in $LOCK"
  [ -n "$expected" ] || die "$LOCK has no checksum for $plat; re-run --update-lock"

  binary="$CACHE/testledger-$version-$plat"
  if [ -x "$binary" ] && [ "$(sha256_of "$binary")" = "$expected" ]; then
    exec "$binary" "$@"
  fi

  mkdir -p "$CACHE"
  local tmp
  tmp="$(mktemp "$CACHE/.download.XXXXXX")"
  # shellcheck disable=SC2064  # $tmp is intentionally expanded now.
  trap "rm -f '$tmp'" EXIT

  echo "testledger: fetching $version for $plat" >&2
  fetch "$version" "testledger-$plat" "$tmp"

  local actual
  actual="$(sha256_of "$tmp")"
  [ "$actual" = "$expected" ] || die "checksum mismatch for testledger-$plat
  expected $expected
  actual   $actual
Refusing to run it. Re-run --update-lock if you meant to change versions."

  chmod +x "$tmp"
  mv "$tmp" "$binary"
  trap - EXIT
  exec "$binary" "$@"
}

main "$@"
